name: chat_app
description: like whatsapp.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  firebase_core: ^2.16.0
  firebase_auth: ^4.10.0
  cloud_firestore: ^4.9.2
  firebase_storage: ^11.2.7
  country_picker: ^2.0.21
  flutter_riverpod: ^2.3.6
  image_picker: ^1.0.1
  flutter_contacts: ^1.1.7
  uuid: ^3.0.7
  intl: ^0.18.1
  cached_network_image: ^3.2.3
  cached_video_player: ^2.0.4
  emoji_picker_flutter: ^1.6.1
  enough_giphy_flutter: ^0.4.0
  flutter_sound: ^9.2.13
  permission_handler: ^10.4.3
  path_provider: ^2.1.0
  audioplayers: ^5.1.0
  swipe_to: ^1.0.2
  story_view: ^0.15.0
  agora_uikit: ^1.3.6
  
dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true


  assets:
    - assets/backgroundImage.png
    - assets/bg.png
